# Generated by Django 3.2.25 on 2026-03-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='link',
        ),
    ]
