# Generated by Django 3.2.25 on 2026-03-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_workout_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
