# Generated by Django 3.2.25 on 2026-03-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='tag',
            field=models.ManyToManyField(to='core.Tag'),
        ),
    ]
