# Generated by Django 3.2.25 on 2026-03-17 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_workout_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='tag',
            new_name='tags',
        ),
    ]
