# Generated by Django 3.2.25 on 2026-03-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20260317_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='exercisies',
            new_name='exercises',
        ),
    ]
