# Generated by Django 3.2.25 on 2026-03-19 12:39

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_exercisies_workout_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.workout_image_file_path),
        ),
    ]
