# Generated by Django 3.2.25 on 2026-03-24 14:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20260323_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='image',
        ),
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.exercise_image_file_path),
        ),
    ]
