# Generated by Django 3.2.25 on 2026-03-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20260324_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
