# Generated by Django 3.2.25 on 2026-03-31 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_exercise_is_public'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='WorkoutTag',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='tags',
        ),
        migrations.AddField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='workout',
            name='wo_tags',
            field=models.ManyToManyField(to='core.WorkoutTag'),
        ),
        migrations.CreateModel(
            name='ExerciseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('muscle', 'Muscle'), ('equipment', 'Equipment'), ('category', 'Category'), ('primary_muscle', 'Primary Muscle'), ('secondary_muscle', 'Secondary Muscle')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name', 'type')},
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='ex_tags',
            field=models.ManyToManyField(to='core.ExerciseTag'),
        ),
    ]
