# Generated by Django 3.2.25 on 2026-03-31 10:42

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20260331_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='image',
        ),
        migrations.AddField(
            model_name='exercise',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.exercise_image_file_path),
        ),
        migrations.AddField(
            model_name='exercise',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.exercise_image_file_path),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='ex_tags',
            field=models.ManyToManyField(blank=True, to='core.ExerciseTag'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='wo_tags',
            field=models.ManyToManyField(blank=True, to='core.WorkoutTag'),
        ),
    ]
