# Generated by Django 3.2.25 on 2026-03-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20260331_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisetag',
            name='type',
            field=models.CharField(choices=[('equipment', 'Equipment'), ('category', 'Category'), ('primary_muscle', 'Primary Muscle'), ('secondary_muscle', 'Secondary Muscle')], max_length=50),
        ),
    ]
