# Generated by Django 3.2.25 on 2026-04-01 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_exercisetag_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='ex_tags',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='core.ExerciseTag'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exercisetag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workout',
            name='wo_tags',
            field=models.ManyToManyField(blank=True, related_name='workouts', to='core.WorkoutTag'),
        ),
        migrations.AlterField(
            model_name='workouttag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_tags', to=settings.AUTH_USER_MODEL),
        ),
    ]
